import numpy as np

arr = [1,2,3,4]
arr2 = [[1,2,3],[1,2,3],[1,2,3]]
ndarr = np.array(arr)
ndarr2 = np.array(arr2)
print("================== Perkalian")
print(arr*3)
print(ndarr*3)
print("================== Array Dua Dimensi")
print(arr2)
print(ndarr2)
print("================== Fungsi Numpy arange")
ndarange = np.arange(0,10)
ndarange2 = np.arange(0,10,3)
print(ndarange)
print(ndarange2)
print("================== Fungsi Numpy zeros and ones")
ndzeros = np.zeros((2,4),dtype=int)
ndones = np.ones((2,4),dtype=int)
print(ndzeros)
print(ndones)
print("================== Fungsi Numpy linspace")
ndlinspace = np.linspace(0,10,100)
print(ndlinspace)
print("================== Fungsi Numpy identity and eye")
ndidentity = np.identity(5)
ndeye = np.eye(3)
print(ndidentity)
print(ndeye)